# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']
        autowire: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Pour la méthode jetonNonTrouve de la classe JwtAuthenticationFailureHandler
    App\Security\JwtAuthenticationFailureHandler:
        tags:
           - { name: 'kernel.event_listener', event: 'lexik_jwt_authentication.on_jwt_not_found', method: 'jetonNonTrouve' }